### ISSUE TITLE
Wellhead range bug?

### ISSUE THREAD

**Issue by mkriss** [Geofinancial/methanescan#17]
Why isn't highlighted 97 score for Conoco not showing up in Wellhead range below? See screenshot below (Note this on Texas/New Mexico border).

![Screen Shot 2020-02-25 at 8 56 29 PM](https://user-images.githubusercontent.com/16269555/75313340-717e1c80-5811-11ea-97fa-1e53cd521134.png)

Question: Are Wellhead range scores for 1yr, 1mo, 24hr or adjustable by checkboxes?

**Comment by npspringer** [comment]
Ah, because the wellhead range widget is linked to the 1 year layer.  So to answer your question, the wellhead range score widget does not update with the checkboxes. Same goes for the producer widget. I can do some more digging to see how I could do this, but haven't been able to crack that nut yet.

What I did do is reorder the layers so the 1yr layer is on top.  So when hovering, the 1yr pop-ups come up first.

**Comment by mkriss** [comment]
Ok, that's fine for now. 

Let's change "Selected Wellhead Score Range" label to: 

"Selected Wellhead Score Range (1yr)"

**Comment by npspringer** [comment]
Done.

**Comment by mkriss** [comment]
:-)
