### ISSUE TITLE
Selected Wellhead Score Range anomaly

### ISSUE THREAD

**Issue by mkriss** [Geofinancial/methanescan#22]
When selecting a data point on the Wellhead Score Range (e.g. 89), the Carto correctly identifies Chevron as the responsible party for the 4 sites. However when zooming on these sites (near Fresno CA), the wellheads are not visible. Refer to screenshot below.

![Screen Shot 2020-02-26 at 6 49 27 PM](https://user-images.githubusercontent.com/16269555/75407986-4525d700-58c9-11ea-996d-8dc95ee50067.png)

**Comment by npspringer** [comment]
They are in the screenshot, just hard to see because of the color scale and size. Look down in the bottom left, just west of Interstate 5. They are also showing up yellow because, as we discussed, the colors rescale when select a subset in the "Select Wellhead Score Widget". Will see if there's anyway to change that.

**Comment by mkriss** [comment]
Ok, great. Yes, we should try to adjust the colors if possible.
